### ISSUE TITLE
Update JAGS reference to 4.0.1

### ISSUE THREAD

**Issue by pmhogan** [poissonconsulting/skeleton#3]

**Comment by pmhogan** [comment]
@Misc{plummer_jags_2015,
  title = {{JAGS} version 4.0.1 user manual},
  url = {http://sourceforge.net/projects/mcmc-jags/files/Manuals/4.x/},
  author = {Martyn Plummer},
  month = {Oct},
  year = {2015},
}

**Comment by joethorley** [comment]
done
